import "./globals.css";
import App from "./app";

export const runtime = "nodejs";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head></head>
      <body className="h-full min-h-screen overflow-x-hidden">
        <App>{children}</App>
      </body>
    </html>
  );
}
